name: annogrid-gateway

services:

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.rootfs=/host'
      - '--collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker|run/docker)($$|/)'
      - '--web.listen-address=0.0.0.0:9100'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    env_file: .env
    volumes:
      - /var/log:/var/log:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    environment:
      - APP_NAME=${APP_NAME}
      - GATEWAY_ID=${GATEWAY_ID}
    command:
      - -config.file=/etc/promtail/config.yml
      - -config.expand-env=true

  docker-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: docker-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      SERVICES: 1
      TASKS: 1
      POST: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "2375:2375"
    read_only: true
    tmpfs:
      - /run

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    env_file: .env
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}

volumes: {}
