global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'netdata-local'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['netdata:19999']

  - job_name: 'nodes'
    static_configs:
      - targets:
          - 'anno-app-opi3b-01:9100'
          - 'anno-ai-jetson-01:9100'
          - 'anno-nas-rpi3b-01:9100'
