global:
  scrape_interval: 15s
  external_labels:
    dataset: ${APP_NAME}
    host: ${GATEWAY_ID}

scrape_configs:
  - job_name: 'cluster-nodes'
    static_configs:
      # Local Node (the RPi3B running this config)
      - targets: ['host.docker.internal:9100']
        labels:
          nodename: 'anno-gw-mon-rpi3b-01'
      
      # Remote Cluster Nodes
      - targets:
          - '100.71.104.20:9100'
          - '100.123.183.36:9100'
          - '100.114.225.52:9100'
          - '100.85.193.50:9100'

  - job_name: 'netdata'
    static_configs:
      - targets: ['netdata:19999']
        labels:
          nodename: 'anno-gw-mon-rpi3b-01'

remote_write:
  - url: "${CENTRAL_PROM_URL}"
    basic_auth:
      username: "${CENTRAL_PROM_USER}"
      password: "${CENTRAL_PROM_TOKEN}"
