name: twenty

services:
  twenty:
    image: twentycrm/twenty:latest
    container_name: twenty_crm
    ports:
      - "${PORT}:${PORT}"
    environment:
      # Database Connection
      - PG_DATABASE_HOST=${PG_DATABASE_HOST}
      - PG_DATABASE_PORT=${PG_DATABASE_PORT}
      - PG_DATABASE_NAME=${PG_DATABASE_NAME}
      - PG_DATABASE_USER=${PG_DATABASE_USER}
      - PG_DATABASE_PASSWORD=${PG_DATABASE_PASSWORD}
      
      # App Routing
      - SERVER_URL=http://${ORANGE_PI_IP}:${PORT}
      - PORT=${PORT}
      
      # Core Engine Config
      - APP_SECRET=${APP_SECRET}
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      homepage.group: anno-app
      homepage.name: Twenty CRM
      homepage.icon: twenty.png
      homepage.href: "http://100.67.194.10:${PORT}"
      homepage.description: Open-source CRM
      homepage.server: anno-app
      homepage.container: twenty_crm
    networks:
      - core-data_default

networks:
  core-data_default:
    external: true
