- _hidden0:
    - anno-app (OrangePi 3B+):
      - icon: mdi-server
        href: http://anno-app-opi3b-01.local
        description: ⠀
    - anno-ai (Jetson Orin Nano):
      - icon: mdi-gpu
        href: http://anno-ai-jetson-orin-nano-01.local
        description: ⠀
    - anno-nas (Raspberry Pi 3B+):
      - icon: mdi-harddisk
        href: http://anno-nas-rpi3b-01.local
        description: ⠀
    - anno-gw (Raspberry Pi 3B+):
      - icon: mdi-router-network
        href: http://anno-gw-mon-rpi3b-01.local
        description: ⠀

- _hidden1:
    - Cloudflare:
      - icon: cloudflare.png
        href: https://dash.cloudflare.com
        description: ⠀
    - Tailscale:
      - icon: tailscale.png
        href: https://login.tailscale.com
        description: ⠀
    - GitHub:
      - icon: github.png
        href: https://github.com/Wanghley/AnnoGrid
        description: ⠀
    - Portainer:
      - icon: portainer.png
        href: https://anno-app-opi3b-01.local:9443
        description: ⠀
