- _hidden0:
    - anno-app Cockpit:
      - icon: mdi-server-cog
        href: "https://100.67.194.10:9090"
        description: ⠀
    - anno-ai Cockpit:
      - icon: mdi-server-cog
        href: "https://100.85.193.50:9090"
        description: ⠀
    - anno-nas Cockpit:
      - icon: mdi-server-cog
        href: "https://100.114.225.52:9090"
        description: ⠀
    - anno-gw Cockpit:
      - icon: mdi-server-cog
        href: "https://100.101.178.87:9090"
        description: ⠀

- _hidden1:
    - Cloudflare:
      - icon: cloudflare.png
        href: https://dash.cloudflare.com
        description: ⠀
    - Tailscale:
      - icon: tailscale.png
        href: https://login.tailscale.com
        description: ⠀
    - GitHub:
      - icon: github.png
        href: https://github.com/Wanghley/AnnoGrid
        description: ⠀
    - Portainer:
      - icon: portainer.png
        href: https://anno-app-opi3b-01.local:9443
        description: ⠀
