server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  # This uses the variable defined in your .env / docker-compose
  - url: http://100.85.193.50:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        # The 'host' label is now handled by the command line in docker-compose
        __path__: /var/log/*log
